# Generated by Django 2.0.6 on 2018-06-28 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(max_length=2)),
                ('severity', models.CharField(max_length=1)),
                ('version', models.CharField(max_length=5)),
                ('timestamp', models.DateTimeField(null=True)),
                ('hostname', models.CharField(max_length=50)),
                ('appname', models.CharField(max_length=50)),
                ('procid', models.CharField(max_length=50)),
                ('msgid', models.CharField(max_length=50)),
                ('structuredData', models.TextField()),
                ('msg', models.TextField()),
            ],
            options={
                'ordering': ['-timestamp', '-severity', 'appname'],
                'permissions': (('get_log', 'Can see list of logs'),),
                'get_latest_by': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=45, unique=True)),
                ('system', models.CharField(choices=[('W', 'Windows'), ('L', 'Linux')], max_length=1)),
                ('counter', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PredefinedReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('generatedFor', models.CharField(max_length=1000)),
                ('numbOfAllLogs', models.BigIntegerField(default=0)),
                ('numbOfAllAlarms', models.BigIntegerField(default=0)),
                ('nOfEmergAlarms', models.BigIntegerField(default=0)),
                ('nOfAlertAlarms', models.BigIntegerField(default=0)),
                ('nOfCritAlarms', models.BigIntegerField(default=0)),
                ('nOfErrAlarms', models.BigIntegerField(default=0)),
                ('nOfWarnAlarms', models.BigIntegerField(default=0)),
                ('nOfNotcAlarms', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='log',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logService.Machine'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['-timestamp', 'msgid'], name='logService__timesta_b28479_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['-timestamp', 'hostname'], name='timestamp_host_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['-timestamp', 'appname'], name='timestamp_app_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['-timestamp'], name='timestamp_idx'),
        ),
    ]
