# Generated by Django 2.0.3 on 2018-04-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.SmallIntegerField()),
                ('severity', models.SmallIntegerField()),
                ('version', models.SmallIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('hostname', models.CharField(max_length=50)),
                ('appname', models.CharField(max_length=50)),
                ('procid', models.CharField(max_length=50)),
                ('msgid', models.CharField(max_length=50)),
                ('structuredData', models.TextField()),
                ('msg', models.TextField()),
            ],
        ),
    ]
