# Generated by Django 2.0.3 on 2018-04-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logService', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
