# Generated by Django 2.0.4 on 2018-05-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logService', '0002_auto_20180403_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=45)),
                ('system', models.CharField(choices=[('W', 'Windows'), ('L', 'Linux')], max_length=1)),
                ('counter', models.BigIntegerField()),
            ],
        ),
    ]
