# Generated by Django 2.0.6 on 2018-06-28 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logService', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regfacility', models.CharField(max_length=100)),
                ('regseverity', models.CharField(max_length=100)),
                ('reghostname', models.CharField(max_length=100)),
                ('regappname', models.CharField(max_length=100)),
                ('regmsgid', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=1000)),
                ('repeat', models.SmallIntegerField()),
                ('type', models.CharField(choices=[('0', 'Emergency'), ('1', 'Alert'), ('2', 'Critical'), ('3', 'Error'), ('4', 'Warning'), ('5', 'Notice')], max_length=1)),
                ('sysspec', models.BooleanField()),
                ('machinespec', models.BooleanField()),
                ('appspec', models.BooleanField()),
                ('rmispec', models.BooleanField()),
                ('minutes', models.SmallIntegerField()),
                ('active', models.BooleanField()),
            ],
            options={
                'permissions': (('get_alarm_rules', 'Can see rules of active alarms'),),
            },
        ),
        migrations.CreateModel(
            name='AlarmLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('seen', models.BooleanField()),
                ('alarm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alarmService.Alarm')),
                ('logs', models.ManyToManyField(to='logService.Log')),
            ],
            options={
                'permissions': (('get_alarms', 'Can see active alarms'),),
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('numbOfAllLogs', models.BigIntegerField(default=0)),
                ('numbOfAllAlarms', models.BigIntegerField(default=0)),
                ('numbOfWinLogs', models.BigIntegerField(default=0)),
                ('numbOfLinLogs', models.BigIntegerField(default=0)),
                ('numbOfWinAlarms', models.BigIntegerField(default=0)),
                ('numbOfLinAlarms', models.BigIntegerField(default=0)),
            ],
            options={
                'permissions': (('get_report', 'Can see report'),),
            },
        ),
    ]
