# Generated by Django 2.0.4 on 2018-05-05 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logService', '0003_machine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regexp', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=1000)),
                ('type', models.CharField(max_length=20)),
                ('repeat', models.SmallIntegerField()),
                ('sysspec', models.BooleanField()),
                ('machinespec', models.BooleanField()),
                ('timed', models.BooleanField()),
                ('hours', models.SmallIntegerField(null=True)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='AlarmLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('seen', models.BooleanField()),
                ('alarm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alarmService.Alarm')),
                ('machine', models.ForeignKey(null=True, on_delete=False, to='logService.Machine')),
            ],
        ),
    ]
