# Generated by Django 2.0.6 on 2018-06-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attempts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=150, null=True)),
                ('lastAttempt', models.DateTimeField(null=True)),
                ('blockDate', models.DateTimeField(null=True)),
                ('counter', models.SmallIntegerField(default=0)),
            ],
        ),
    ]
